CREATE TABLE analyses (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    title VARCHAR(200) NOT NULL COMMENT '项目名称',
    description TEXT COMMENT '项目描述',
    creation_type ENUM('ai', 'manual') NOT NULL COMMENT '创建方式',
    repo_url VARCHAR(500) COMMENT 'GitHub仓库地址',
    start_struct VARCHAR(100) COMMENT '起始结构体',
    analysis_depth INT COMMENT '分析深度',
    model_name VARCHAR(50) COMMENT '使用的模型',
    diagram_oss_url VARCHAR(500) COMMENT '框图JSON的OSS地址',
    diagram_size INT COMMENT '压缩后大小(bytes)',
    status ENUM('draft', 'pending', 'analyzing', 'completed', 'failed') DEFAULT 'draft' COMMENT '状态',
    error_message TEXT COMMENT '错误信息',
    started_at DATETIME COMMENT '分析开始时间',
    completed_at DATETIME COMMENT '分析完成时间',
    is_public BOOLEAN DEFAULT FALSE COMMENT '是否公开分享',
    shared_at DATETIME COMMENT '分享时间',
    share_title VARCHAR(200) COMMENT '分享标题',
    share_description TEXT COMMENT '分享描述',
    tags JSON COMMENT '标签数组',
    view_count INT DEFAULT 0 COMMENT '浏览数',
    like_count INT DEFAULT 0 COMMENT '点赞数',
    comment_count INT DEFAULT 0 COMMENT '评论数',
    bookmark_count INT DEFAULT 0 COMMENT '收藏数',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_is_public (is_public),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_shared_at (shared_at),
    FULLTEXT INDEX ft_share_title_desc (share_title, share_description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分析项目表';
