CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL COMMENT '用户名',
    email VARCHAR(100) UNIQUE COMMENT '邮箱',
    password_hash VARCHAR(255) COMMENT '密码哈希',
    avatar_url VARCHAR(500) DEFAULT '' COMMENT '头像URL',
    bio TEXT COMMENT '个人简介',
    github_id VARCHAR(50) UNIQUE COMMENT 'GitHub ID',
    wechat_openid VARCHAR(100) UNIQUE COMMENT '微信OpenID',
    subscription_level ENUM('free', 'basic', 'pro') DEFAULT 'free' COMMENT '套餐级别',
    daily_quota INT DEFAULT 5 COMMENT '每日配额',
    quota_used_today INT DEFAULT 0 COMMENT '今日已用配额',
    quota_reset_at DATETIME COMMENT '配额重置时间',
    subscription_expires_at DATETIME COMMENT '订阅过期时间',
    email_verified BOOLEAN DEFAULT FALSE COMMENT '邮箱是否验证',
    verification_code VARCHAR(100) COMMENT '验证码',
    verification_expires_at DATETIME COMMENT '验证码过期时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_github_id (github_id),
    INDEX idx_wechat_openid (wechat_openid),
    INDEX idx_email (email),
    INDEX idx_verification_code (verification_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
